openapi: 3.0.3
info:
  title: Patient Service API
  version: '1.0'
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /patients:
    get:
      summary: Retrieve list of patients
      parameters:
        - name: offset
          in: query
          description: Pagination offset
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          description: Pagination limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: A list of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create new patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientCreate'
      responses:
        '201':
          description: Patient created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict - duplicate entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /patients/{id}:
    get:
      summary: Get a patient by ID
      parameters:
        - name: id
          in: path
          description: Patient unique identifier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Patient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Patient not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a patient by ID
      parameters:
        - name: id
          in: path
          description: Patient unique identifier
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientUpdate'
      responses:
        '200':
          description: Patient updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Patient not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict - concurrent modification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Patient:
      type: object
      required:
        - id
        - fullName
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        fullName:
          type: string
          example: "Ivan Ivanov"
        birthDate:
          type: string
          format: date
          example: "1980-12-12"
        email:
          type: string
          format: email
          example: "ivan.ivanov@example.com"
    PatientCreate:
      type: object
      required:
        - fullName
      properties:
        fullName:
          type: string
          example: "Ivan Ivanov"
        birthDate:
          type: string
          format: date
          example: "1980-12-12"
        email:
          type: string
          format: email
          example: "ivan.ivanov@example.com"
    PatientUpdate:
      type: object
      properties:
        fullName:
          type: string
          example: "Ivan Ivanov"
        birthDate:
          type: string
          format: date
          example: "1980-12-12"
        email:
          type: string
          format: email
          example: "ivan.ivanov@example.com"
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Invalid request parameters"
